name: Lint & Build

on:
  push:
    branches: [ "**" ]
  pull_request:

concurrency:                # cancel stale runs on the same branch/PR
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm                # native dependency cache :contentReference[oaicite:0]{index=0}

      - name: Install dependencies
        run: npm ci                 # fast, lock‑file‑exact install

      # ---------- Lint & formatting ----------
      - name: ESLint
        run: npm run lint

      - name: Prettier check
        run: npm run format

      - name: Type‑check
        run: npx tsc --noEmit

      # ---------- Build ----------
      - name: Build (tsc + chmod)
        run: npm run build
